/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Input */

#ifndef _Included_Input
#define _Included_Input
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Input
 * Method:    MapPrint
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_Input_MapPrint
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
