/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Input */

#ifndef _Included_Input
#define _Included_Input
#ifdef __cplusplus
extern "C" {
#endif
#undef Input_MAXLEN
#define Input_MAXLEN 20L
/*
 * Class:     Input
 * Method:    getColorInfo
 * Signature: ([I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Input_getColorInfo
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
